AWSTemplateFormatVersion: '2010-09-09'
Description: 'Security Group example'
Parameters:
  Env:
    Descriptions: Environment
    Type: String
  SubnetId:
    Descriptions: Subnet in which MT reside
    Type: String
  ExampleSecurityGroup:
    Descriptions: Security group that can mount efs
    Type: String
  KMSKeyArn:
    Descriptions: Key used for EFS encryption
    Type: String

Resources:
  # Elastic file system
  ExampleEFS:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose
      Encrypted: true
      KmsKeyId: !Ref KMSKeyArn
      FileSystemTags:
        - Key: project
          Value: example-project
      FileSystemPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - elasticfilesystem:ClientMount
              - elasticfilesystem:ClientWrite
              - elasticfilesystem:ClientRootAccess
            Principal:
              AWS: '*'

  # Access point for elastic file system
  ExampleAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref ExampleEFS
      PosixUser:
        Uid: 1000
        Gid: 1000
      RootDirectory:
        CreationInfo:
          OwnerGid: 1000
          OwnerUid: 1000
          Permissions: 0777
        Path: '/mnt/efs'
      AccessPointTags:
        - Key: project
          Value: example-project

  # Mounting target
  ExampleMountingTarget:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref ExampleFileSystem
      SubnetId: !Ref SubnetId
      SecurityGroups:
        - !Ref ExampleSecurityGroup

